### ISSUE TITLE
Show last Drone position on reconnect

### ISSUE THREAD

**Issue by Pomaroli** [DroidPlanner/droidplanner#1350]
Lets say we have an crash scenario. During crash the telemetry and GPS module has been damaged but we have still battery power on the system and we have also an weak signal. 
DP was disconnected and we see the last Drone position on the screen. Now we walk to the shown position to pickup the drone. While we are coming closer to the drone DP is re-connecting to the drone.
On the dp Screen the Drone position is reset to Home Position so we can see anymore were the Drone is. probably caused because the GPS signal is lost ?
The Drone position should not be reset.

**Comment by ne0fhyk** [comment]
The ability to see the last drone position will be served by the `Flight History` section. 
It uses the available telemetry logs to retrieve the last available drone GPS location. That section is currently available on the DP3 beta, but is not working because of some bugs. 
It'll be fixed, and fully working on the next beta release of DP3 though.
