### ISSUE TITLE
make Speech sentence editable

### ISSUE THREAD

**Issue by Pomaroli** [DroidPlanner/droidplanner#1351]
Could it be possible to make the speech sentence editable ?

**Comment by ne0fhyk** [comment]
@Pomaroli you can suggest new or improvements to the current speech sentences. Making them editable seems like too much work for a feature that would be rarely used.

**Comment by Pomaroli** [comment]
Hi,
yes i understand, is there no way to edit them on XMl file ?
The problem are the trasnlations in other languages, an example, for German it should not say stabilize but something like "Manuel" otherwise the speech is laughable. I can do the senteces for german if you can give me the english default.

**Comment by ne0fhyk** [comment]
@Pomaroli The devs contributing to the german translation are @zumbrunnen and @squilter . Perhaps you might want to check with them regarding the correct term.

**Comment by zumbrunnen** [comment]
Hi @Pomaroli 

A lot of things (e.g. the flight modes, RC/tuning params) are still hard-coded in English. In order to translate them, we first have to change the code to use localized variables. After that, it is as simple as populating the XML files with the localized contents.

If you point me to the right direction, I'll change the code and translate stuff to German. Please give me your priorities. :wink: Shall I cast an eye on the spoken flight modes to begin?

**Comment by Pomaroli** [comment]
Hi,
yes this is a good idea. Sorry for delay.
